# tweets from my old shitposting twitter account
tweets = [
	"what are you talking about?",
	"chicken, kentucky f",
	"we were played for absolute fools",
	"10 22 34 40 the numbers in my head\nand can't get them out",
	"make it stop make it stop i never forget this i never",
	"i want to forget",
	"ha ha",
	"nooo weather kinda popping tho",
	"may",
	"why when u say iq of 4 it's like bad but then gpa of 4 is good????",
	"sports is crazy"
	"good night i will talk to u tomorrow :)",
	"gm there is a helicopter outside",
	"eh maybe i'm feeling a little good rn",
	"hola",
	"i don't think this guy dostoevsky making shit up so sad",
	"a pleasant breeze today",
	"there are warrants for my arrest in 24 states and 13 foreign countries due to my weapons trafficking ring",
	"i am currently on the run for sending weapons to west african rebel groups in order to control the uranium market",
	"can i get a water with cream",
	"I AM AN INSECT like a little fly go bzz bzzzzz around hanging out on a leaf in the nice weather we have today",
	"happy friday",
	"had a good day i saw the ocean it was nice tired from the week tho",
	"feeling good confident about myself",
	"some people i despise and i hold a great hatred to...\n\njohn mulaney\n\nstop having such an annoying voice john mulaney i'm talking to u, and try being funny some day as well",
	"ever go to connecticut?",
	"fuck i never want to go to connecticut",
	"4 dogecoin",
	"stop buying gas buy burrito with lots of beans then u get a nice food and then be making gas :)",
	"I WILL never be known to the world I AM forever A SET OF CHARACTERS who changes in different situations\n\nNEVER WILL I BE KNOWN\n\nthe filth of this world does not provide reason to show\n\nYOU MAY THINK YOU KNOW ME\n\ni play along with the assumptions of those who despise me",
	"someone stared at me today i think",
	"noooooo i would say it is too warm outside now",
	"good day",
	"simp\n\nson\n\nwowwwwwwwww",
	"it is good to be hopeful for tomorrow",
	"have a good week :)",
	"good weather today got burger",
	"OH MOTHER I CAN FEEL THE SOIL FALLING OVER MY HEAD\nOH MOTHER I CAN FEEL THE SOIL FALLING OVER MY HEAD\nOH MOTHER I CAN FEEL THE SOIL FALLING OVER MY HEAD\nOH MOTHER I CAN FEEL THE SOIL FALLING OVER MY HEAD\nOH MOTHER I CAN FEEL THE SOIL FALLING OVER MY HEAD",
	"there is a point where a tragedy becomes a comedy",
	"the last vestiges of humanity have long disappeared",
	"the big guy himself............?",
	"NEVER NEVER NEVER I NEVER FORGET NEVER NEVER",
	"I WANT TO FORGET",
	"remember to brush your teeth",
	"dog and fish little fishy fish",
	"charlsday",
	"dear fbi agents, all my posts are real, i am a threat to society",
	"i have ascended",
	"saturday",
	"today was a good day",
	"a little rain today",
	"goooooooooooooooooooooooooooooooooooood morning vietnam",
	"what is the reason",
	"her: babe wyd\nme: just got ~\nher: what\nme: the home in unix\nher: wow u are a nerd let's kiss\n\nthis is not real",
	"sometimes i need some time\non my own",
	"my head is angry it is giving me pains",
	"aaaaaahhhhhhhhhhhhh hey",
	"when will it be warm outside for real",
	"who am i",
	"tfw i don't get a kiss for being irish",
	"yea sometimes i'm irish",
	"i don't like when there are people being mean and people fighting and wars",
	"i piss on the shit",
	"good morning a fine chewsday",
	"why every night i am alone",
	"almost 3pm now",
	"am i doomer coomer bloomer i think i act like bloomer but in my mind probably like 70% doomer 25% coomer 5% bloomer",
	"go to the beach where the weather is nice and the shells are pretty",
	"tired",
	"hey",
	"happy",
	"good morning have a good day everyone :)",
	"heyyyyyyyyyyyyy",
	"hi everyone how was your day",
	"chewsday evening",
	"hi it's some nice weather today i think",
	"how fast are you gonna run as fast as a leopard lets see you do it",
	"hi women thank you for existing ur great",
	"go to college they said but i just want to live my own life!",
	"i never actually been to kfc i been to five guys tho!",
	"i cum in the fuck",
	"oh how quaint....... NO STOP you put so many offices in my city!!! i think we lost our charm now just like anywhere else",
	"to the cooler 20 days .....",
	"good afternoon",
	"fuck john mulaney",
	"i have a burning, passionate hatred for john mulaney",
	"hypothetically speaking if you touched a chicken nugget you touched a boob",
	"thursday evenig",
	"heyy hey hey don't",
	"pondering",
	"brooooooooooooooooo.............. hi",
	"today is monday",
	"need real human connection",
	"unironically lonely rn",
	"every minute i sit in this room i get weaker",
	"whoever is reading this",
	"woop woop woop wopp woop doo doo doo doo this is the end doo doo doo on a mission the man is crazy...",
	"i think i should try to be serious for a while ahahah",
	"sell the ice machine",
	"fuck i have to pay taxes",
	"hi i'm",
	"looking for female i can go on a date to five guys with and play minecraft with me and laugh and be happy together 🥺",
	"the tenn tonnnnnn truckkkkkkkkk",
	"i never been to kfc my bad",
	"i think too much coffee is what is causing my constant feeling of dehydration despite drinking like a gallon of water a day",
	"hi",
	"every monday feels like thursday and every tuesday feels like friday then wednesday will feel like monday thursday tuesday friday wednesday and then weekend",
	"broooooooooooooooooo i want pumpkin pie rn",
	"jjjkkkjjjhhhhjjkkjkllljhjkkjkjkkjkkihello<esc>wq",
	"amazon is tripping rn",
	"oh boy this is a scary day"
]
